# generated by datamodel-codegen:
#   filename:  testmo_project_run.json
#   timestamp: 2025-07-02T15:05:45+00:00

from __future__ import annotations

from typing import List, Any, Union

from pydantic import BaseModel


class Model(BaseModel):
    closed_at: Any = None
    closed_by: Any = None
    completed_count: int
    config_id: Any = None
    created_at: str
    created_by: int
    elapsed: Any = None
    failure_count: int
    forecast: Any = None
    forecast_completed: Any = None
    id: int
    is_closed: bool
    is_started: bool
    issues: List
    links: List
    milestone_id: Any = None
    name: str
    project_id: int
    started_at: Union[str, None]
    state_id: int
    status10_count: int
    status11_count: int
    status12_count: int
    status13_count: int
    status14_count: int
    status15_count: int
    status16_count: int
    status17_count: int
    status18_count: int
    status19_count: int
    status1_count: int
    status20_count: int
    status21_count: int
    status22_count: int
    status23_count: int
    status24_count: int
    status2_count: int
    status3_count: int
    status4_count: int
    status5_count: int
    status6_count: int
    status7_count: int
    status8_count: int
    status9_count: int
    success_count: int
    tags: List
    total_count: int
    untested_count: int
    updated_at: Any = None
    updated_by: Any = None


def from_data(json_data) -> Model:
    import json
    data = json_data
    if isinstance(json_data, str):
        data = json.loads(data)
    return Model.model_validate(data)
